name: Pull Request Checker

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}

      - name: Run TypeScript type checking
        run: pnpm run typecheck
      
      - name: Run linting
        run: pnpm run lint
      
      - name: Run tests
        run: pnpm run test
      
      - name: Check for unused dependencies
        run: pnpm run knip
        continue-on-error: true
      
      - name: Build project
        run: pnpm run build
